set(GLFW3_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/include")
set(GLFW3_LIBRARY "${CMAKE_CURRENT_LIST_DIR}/lib/libglfw3.a")
set(GLFW3_LIBRARY_DIR "${CMAKE_CURRENT_LIST_DIR}/lib")

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    GLFW3
    FOUND_VAR GLFW3_FOUND
    REQUIRED_VARS GLFW3_LIBRARY GLFW3_INCLUDE_DIR
)

set(GLFW3_LIBRARIES ${GLFW3_LIBRARY})
set(GLFW3_INCLUDE_DIRS ${GLFW3_INCLUDE_DIR})

mark_as_advanced(GLFW3_INCLUDE_DIR GLFW3_LIBRARY)
